// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQwnqqbiSy28OUR72Q3LxJEpHBYrfBKPQ',
    appId: '1:375043162370:web:9289fa6ef7aeede501421b',
    messagingSenderId: '375043162370',
    projectId: 'chat-flutter-bfa87',
    authDomain: 'chat-flutter-bfa87.firebaseapp.com',
    storageBucket: 'chat-flutter-bfa87.appspot.com',
    measurementId: 'G-EB0NVEX25R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkIpqrGdd6pM32uFrY8kqzKtuZVAe7j4Y',
    appId: '1:375043162370:android:1fc83db3bd726a0d01421b',
    messagingSenderId: '375043162370',
    projectId: 'chat-flutter-bfa87',
    storageBucket: 'chat-flutter-bfa87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGYUkAaApVeWHcUxnXHWCeDt0FhqUF5ps',
    appId: '1:375043162370:ios:2f04b10cce11a03501421b',
    messagingSenderId: '375043162370',
    projectId: 'chat-flutter-bfa87',
    storageBucket: 'chat-flutter-bfa87.appspot.com',
    iosClientId: '375043162370-p68hb1bejbglkjq43t0o9o6dvrr82mev.apps.googleusercontent.com',
    iosBundleId: 'com.chatapp.chatapp',
  );
}
